name: api_uas_perpustakaan
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

dependencies:
  args: ^2.3.0
  crypto: ^3.0.3
  intl: ^0.19.0
  mysql1: ^0.20.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  string_validator: ^1.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
